version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-app
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  mysql:
    image: docker.io/mysql:8
    container_name: mysql-app
    environment:
      - MYSQL_ROOT_PASSWORD=Chaugn@rs2
      - MYSQL_DATABASE=self_project
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - MYSQL_ADDR=root:Chaugn@rs2@tcp(mysql:3306)/self_project?charset=utf8&parseTime=True&loc=Local&multiStatements=true
      - REDIS_ADDRS=redis:6379
      - HOST=0.0.0.0:8080
      - GOOGLE_APPLICATION_CREDENTIALS=credentials/google/.gg_app.json
      - TOKEN_SECRET_KEY=secret
      - GIN_MODE=release

volumes:
  redis-data:
    driver: local
  mysql-data:
    driver: local
