version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-app
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  mysql:
    image: docker.io/mysql:8
    container_name: mysql-app
    environment:
      - MYSQL_ROOT_PASSWORD=Chaugn@rs2
      - MYSQL_DATABASE=self_project
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  redis-data:
    driver: local
  mysql-data:
    driver: local
