// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/thangpham4/self-project/apps/product_server_internal"
	"github.com/thangpham4/self-project/handlers"
	"github.com/thangpham4/self-project/infra"
	"github.com/thangpham4/self-project/pkg/kvredis"
	"github.com/thangpham4/self-project/repo/cache"
	"github.com/thangpham4/self-project/repo/mysql"
	"github.com/thangpham4/self-project/services"
)

// Injectors from wire.go:

func BuildServer(contextContext context.Context) (*gin.Engine, error) {
	redisConfig := infra.NewRedisConfig()
	client, err := infra.NewRedisClient(contextContext, redisConfig)
	if err != nil {
		return nil, err
	}
	kvRedisImpl := kvredis.NewKVRedis(client)
	db, err := infra.NewMySQLConnection()
	if err != nil {
		return nil, err
	}
	productInfoMysql := mysql.NewProductInfoMysql(db)
	productInfoCache := cache.NewProductInfoCache(kvRedisImpl, productInfoMysql)
	productInfoService := services.NewProductInfoService(productInfoCache)
	userAdminMysql := mysql.NewUserAdminMysql(db)
	userAdminService := services.NewUserAdminService(userAdminMysql)
	authorizationService := services.NewAuthorizationService(userAdminService)
	productInfoHandler := handlers.NewProductInfoHandler(productInfoService, userAdminService, authorizationService)
	engine := productserver.NewHTTPserver(productInfoHandler)
	return engine, nil
}
