name: Lint Build
on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-n-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
          cache: true

      - run: go mod download
        name: Cache gomod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.0
          args: --timeout 600s
          only-new-issues: false
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Run Unit Test
        run: make test-unit -j "$(nproc)"
